#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro package install sshfs <args...>"
  echo ""
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  which sshfs >>/dev/null 2>&1
  if [ "$?" != "0" ]; then
    if [ "$(os::is_macos)" = "true" ]; then
      log::error "sshfs not supported on Mac OS now."
      exit 1
    fi

    pm install -y sshfs
  fi

  log::success "install sshfs success."
}

run() {
  core $@
}

run $@
